// MOF file that launches a script whenever a user logs on to the system.
//   The script writes only very basic user data to C:\Logon.txt

#pragma namespace ("\\\\.\\root\\subscription")

instance of __EventFilter as $Filter
{
  Name = "LogonFilter";
    Query = "SELECT * FROM __InstanceCreationEvent WITHIN 15" 
              "WHERE TargetInstance ISA \"Win32_LogonSession\" ";
  QueryLanguage = "WQL";
  EventNamespace = "root\\cimv2";
};

instance of ActiveScriptEventConsumer as $Consumer
{
  Name = "LogonConsumer";
  ScriptingEngine = "VBScript";
    
  ScriptText =
    "Dim file_obj, file\n"
    "Set file_obj = CreateObject(\"Scripting.FileSystemObject\")\n"
    "Set file = file_obj.OpenTextFile(\"C:\\Logon.txt\",8, true)\n"
    "file.WriteLine(\"Logon Session \" & Now)\n"
    "file.WriteLine(\"   Authentication: \" "
	          "& TargetEvent.TargetInstance.AuthenticationPackage )\n"
    "file.WriteLine(\"   Caption: \" "
	          "& TargetEvent.TargetInstance.Caption )\n"
    "file.WriteLine(\"   Description: \" "
	          "& TargetEvent.TargetInstance.Description )\n"
    "file.WriteLine(\"   LogonID: \" "
	          "& TargetEvent.TargetInstance.LogonID )\n"
    "file.WriteLine(\"   LogonType: \" "
	          "& TargetEvent.TargetInstance.LogonType )\n"
    "file.WriteLine(\"   Name: \" "
	          "& TargetEvent.TargetInstance.Name )\n"
    "file.WriteLine(\"   Status: \" "
	          "& TargetEvent.TargetInstance.Status )\n"
      
// This completes writing the available data

    "file.Close\n";
};

instance of __FilterToConsumerBinding
{
  Filter = $Filter;
  Consumer = $Consumer;
};
