# PowerShell script that loops through the logs on all of the computers in the domain looking for events
# 4656 and 4663; these are generated by file auditing for access to an object or requesting a handle to
# an object. If the changes in user startup directories are audited, then this script will note them.
# It will also note changes to any other auditied directories or files, and so should be further modified 
# before use.

foreach($system in Get-AdComputer -Filter *){
  $computername = $system.name
  $computername
  $currenttime =  Get-Date
  $threehoursago = $currenttime.AddHours(-3)
  Get-WinEvent -Computer $computername -FilterHashtable @{`
          logname='Security'; `
          id=4656,4663; `
          StartTime=$threehoursago} -ErrorAction SilentlyContinue
  }
